version: "3.3"

services:
  web:
    image: registry.joinfirefish.org/firefish/firefish
    restart: always
    depends_on:
      - db
      - redis
      - sonic
    ports:
      - "172.17.0.1:54824:3000"
    environment:
      NODE_ENV: production
    volumes:
      - ./storage/files:/firefish/files
      - ./storage/.config:/firefish/.config:ro

  redis:
    image: elestio/redis:7.0
    restart: always
    volumes:
      - ./storage/redis:/data

  db:
    image: elestio/postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./storage/db:/var/lib/postgresql/data

  ### Only one of the below should be used.
  ### Meilisearch is better overall, but resource-intensive. Sonic is a very light full text search engine.

  sonic:
    image: docker.io/valeriansaliou/sonic:v1.4.0
    restart: always
    logging:
      driver: none
    volumes:
      - ./storage/sonic:/var/lib/sonic/store
      - ./storage/sonic/config.cfg:/etc/sonic.cfg
